### ISSUE TITLE
Nice software. It's great!

### ISSUE THREAD

**Issue by unisqu** [karlseguin/ccache#18]
I'm using it but can you help save memory / garbage collection time by looking into this cache below?
https://github.com/coocood/freecache

I hope it can be optimally used like freecache without a lot of GC happening. How does ccache compared with it? I will be using ccache frequently.

**Comment by karlseguin** [comment]
I only looked briefly at Freecache, but they are so different, they can't really be compared. From what I can tell, Freecache only accepts byte[] values. So if you want to store structs, you'll be constantly marshaling and unmarshaling them which may or may not be a big performance hit depending on what you're doing.

Ccache behaves more like a concurrent map with item expiry via an LRU.

It's a little bloated with features like Tracking and LayeredCache. This adds complexity to the library and a little clutter to the actual runtime performance.
