### ISSUE TITLE
OnDelete is not called when an item is evicted for size reasons

### ISSUE THREAD

**Issue by pkaeding** [karlseguin/ccache#21]
I might be missing something, but it seems that the `OnDelete` callback is not called when an item is removed because the size limit is reached. I think we'd just need to add these lines into the `gc` function:

```
if c.onDelete != nil {
	c.onDelete(item)
}
```

Does that sound right?

**Comment by karlseguin** [comment]
I think so, @alexejk agree?

**Comment by alexejk** [comment]
Sounds reasonable. I've sent a PR to fix that & a test to cover it

**Comment by karlseguin** [comment]
thanks!
