### ISSUE TITLE
Fetch returns expired items

### ISSUE THREAD

**Issue by dvdplm** [karlseguin/ccache#4]
I would expect `Fetch()` to behave a little differently and not return stale items. Instead it seems like the `fetch` function argument is invoked only if the item is missing entirely from the cache.
Would you be open to PRs changing that behavior, or provide a `FetchAndRefresh()` that runs the `fetch` function both if the item is expired and missing?

Essentially this:

```go
func (c *Cache) Fetch(key string, duration time.Duration, fetch func() (interface{}, error)) (*Item, error) {
	item := c.Get(key)
	if item != nil && !item.Expired() {
		return item, nil
	}
	value, err := fetch()
	if err != nil {
		return nil, err
	}
	return c.set(key, value, duration), nil
}
```

**Comment by karlseguin** [comment]
I think changing the behavior of `Fetch` is warranted. Anyone who possibly wants a stale value can achieve it themselves. PR welcomed

**Comment by dvdplm** [comment]
See PR #5

**Comment by utrack** [comment]
I think it can be closed?

**Comment by dvdplm** [comment]
I agree.
