### ISSUE TITLE
Allow to change MaxSize while running

### ISSUE THREAD

**Issue by bep** [karlseguin/ccache#41]
First, thanks for this library, I tested this [here](https://github.com/gohugoio/hugo/issues/7425) and it works great.

I have one challenge (which I may just skip in its first version) though, and that is how to control the size of the cache.

I understand that you can somehow control this by implementing `Size()` (the same strategy as used by [Ristretto](https://github.com/dgraph-io/ristretto), but implementing that in a general way for structs/maps seems to be non-trivial. For my use case I can probably do some approximations.

Which is why I'm lifting the idea about a `SetMaxSize` method that could be adjust while running to handle "low on memory" situations.

**Comment by karlseguin** [comment]
https://github.com/karlseguin/ccache/commit/40275a30c8889bd6a3f230892801c26a181917e1

?

**Comment by bep** [comment]
Yes, that looks great.

**Comment by karlseguin** [comment]
This is in master now. Thanks for the suggestion!

**Comment by bep** [comment]
Just tested it -- works great. I still need to do some thinking about "how to best" do these adjustments, but this is a much simpler mental model than the other one. I think this will be useful to many, thanks again.
