### ISSUE TITLE
How to traverse all items in the cache?

### ISSUE THREAD

**Issue by HDT3213** [karlseguin/ccache#54]

**Comment by karlseguin** [comment]
Cannot. But there's a DeletePrefix that could be used as a base for implementing this. I can look at it as it should be quite easy. Mind explaining the use-case a little more?

**Comment by HDT3213** [comment]
I want to search for elements that meet certain conditions in the cached collection

**Comment by karlseguin** [comment]
Does this solve your requirement?
https://github.com/karlseguin/ccache/commit/bcaca36409e144647174b5a87d235eb5ba0a3780

**Comment by HDT3213** [comment]
I think if I could break the for each in advance would be better. How about this: [pull#55](https://github.com/karlseguin/ccache/pull/55)

**Comment by karlseguin** [comment]
I like your approach.

https://github.com/karlseguin/ccache/commit/ae1872d7009cf48f9441f62753360265b4016da7

Makes the name consistent with the DeleteFunc function, applies the same logic to the layered cache, and adds test.

**Comment by HDT3213** [comment]
I think it satisfies my needs perfectly. Thank you very much! I'm looking forward to your next release.
