### ISSUE TITLE
gc will remove incorrect number of items

### ISSUE THREAD

**Issue by oOvalm** [karlseguin/ccache#97]
[here](https://github.com/karlseguin/ccache/blob/master/cache.go#L367)，The number of items pruned should not depend on its size. If items are large, it will lead to prune all the items

```go
type SizeByte []byte

func (s SizeByte) Size() int64 {
	return int64(len(s))
}

func genStringWithLen(l int) SizeByte {
	bytes := make([]byte, l)
	return bytes
}

func main() {
	cc := ccache.New[SizeByte](ccache.Configure[SizeByte]().MaxSize(100).ItemsToPrune(2))
	for i := 0; i < 10; i++ {
		key := strconv.Itoa(i)
		val := genStringWithLen(10)
		cc.Set(key, val, time.Hour)
	}
	time.Sleep(time.Millisecond * 10)
	println(cc.GetSize(), cc.ItemCount()) // 100 10
	cc.Set("otherKey", genStringWithLen(10), time.Hour)
	println(cc.GetSize(), cc.ItemCount()) // 10 1 (it should be `90 9`)
}
```

**Comment by karlseguin** [comment]
Hmm..I think `ItemsToPrune` does exactly what it says.

But I agree that isn't the most useful behavior. In the branch linked above, I've replaced `ItemsToPrune` with `PercentToPrune`, defaulting to 10 (10%). Does that make more sense to you?

**Comment by oOvalm** [comment]
this cache supports `Size`, shouldn't it ensure that the maximum occupied Size does not exceed `MaxSize`?
I think a reasonable implementation is: prune until `Size < MaxSize`

**Comment by oOvalm** [comment]
After trying your implementation, it seems more reasonable(compare with my thought)

**Comment by temka-io** [comment]
@karlseguin 
Hi! Could you please create a new release that includes the fix from this issue?

**Comment by karlseguin** [comment]
@temka-io https://github.com/karlseguin/ccache/releases/tag/v3.0.7
